<?php
/** @package Cars::Model::DAO */

/** import supporting libraries */
require_once("verysimple/Phreeze/Phreezable.php");
require_once("MakeMap.php");

/**
 * MakeDAO provides object-oriented access to the Make table.  This
 * class is automatically generated by ClassBuilder.
 *
 * WARNING: THIS IS AN AUTO-GENERATED FILE
 *
 * This file should generally not be edited by hand except in special circumstances.
 * Add any custom business logic to the Model class which is extended from this DAO class.
 * Leaving this file alone will allow easy re-generation of all DAOs in the event of schema changes
 *
 * @package Cars::Model::DAO
 * @author ClassBuilder
 * @version 1.0
 */
class MakeDAO extends Phreezable
{
	/** @var string */
	public $Model;

	/** @var string */
	public $Reviews;

	/** @var string */
	public $Makename;

	/** @var int */
	public $Vin;



}
?>